version: "3.9"

volumes:
  pgdata:

services:
  postgresql:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: netology_stocks_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ./
    command: gunicorn stocks_products.wsgi:application -b 0.0.0.0:8000
    volumes:
      - ./static/:/static/
    env_file:
      ./.env
    depends_on:
      - postgresql

  nginx:
    build: ./nginx
    volumes:
      - ./static/:/static/:ro
    ports:
      - 8001:80
    depends_on:
      - web
